### ISSUE TITLE
Calling _exit

### ISSUE THREAD

**Issue by daurnimator** [justincormack/ljsyscall#171]
I'm trying to call the syscall `_exit`.
But `_exit` is replaced with `exit_group` in libc.lua: https://github.com/justincormack/ljsyscall/blob/master/syscall/libc.lua#L48

**Comment by justincormack** [comment]
I can't quite remember why I did this it doesn't seem to make that much sense...

**Comment by justincormack** [comment]
oops, typo in commit message, fixed.
