### ISSUE TITLE
musl-static-luajit syscall support

### ISSUE THREAD

**Issue by houseofkodai** [justincormack/ljsyscall#174]
I do understand that musl does not have dlopen support for static binaries.
could we not have kernel-syscall support without any libc - so ffi.C.syscall can be used ?!.

**Comment by justincormack** [comment]
Static binaries work fine. Obviously you cannot use dlopen, but you can write a different module loader, or write a fake dlopen. Look in examples/ at dl.c and the cbuild.sh script for a rough idea of what to do.

**Comment by houseofkodai** [comment]
I do apologize for not going through the samples before posting this issue - thanks for pointing me in the right direction.
