### ISSUE TITLE
No atexit on Ubuntu 14.04/15.04

### ISSUE THREAD

**Issue by lukego** [justincormack/ljsyscall#180]
I have no `syscall.atexit` function available when running on Ubuntu 14.04 or 15.05. Is this expected?

```
$ luajit
LuaJIT 2.1.0-alpha -- Copyright (C) 2005-2015 Mike Pall. http://luajit.org/
JIT: ON SSE2 SSE3 SSE4.1 fold cse dce fwd dse narrow loop abc sink fuse
> S = require("syscall")
> =S.atexit
nil
```

Digging in a little bit by adding a debug printout it seems like ljsyscall is trying to detect whether this is available in libc, and deciding that it is not:

```
./syscall/libc.lua:56: missing declaration for symbol 'exit'
```

**Comment by lukego** [comment]
Got some funny behavior with bb6682a:

```
$ sudo rlwrap ~/git/snabbswitch/deps/luajit/src/luajit                                               
LuaJIT 2.1.0-alpha -- Copyright (C) 2005-2015 Mike Pall. http://luajit.org/
JIT: ON SSE2 SSE3 SSE4.1 fold cse dce fwd dse narrow loop abc sink fuse
> S = require("syscall")
> =S.atexit
function: 0x41fb7460
> S.atexit(function () print("dead") end)
> ^D
rlwrap: warning: luajit crashed, killed by SIGSEGV (core dumped).
rlwrap itself has not crashed, but for transparency,
it will now kill itself with the same signal


warnings can be silenced by the --no-warnings (-n) option
```

**Comment by justincormack** [comment]
Yes, I think you need to be careful that there is an explicit exit() while luajit is still live, eg
````
luajit
LuaJIT 2.0.3 -- Copyright (C) 2005-2014 Mike Pall. http://luajit.org/
JIT: ON CMOV SSE2 SSE3 SSE4.1 fold cse dce fwd dse narrow loop abc sink fuse
> S = require("syscall")
> S.atexit(function () print("dead") end)
> S.exit()
dead
````

**Comment by lukego** [comment]
My bad. I had thought that `atexit()` was executing code even e.g. when killed by SIGTERM. Could be that it is not the mechanism that we are looking for anyway.

**Comment by justincormack** [comment]
Yes, atexit is just called from exit() in libc. Currently signal handling functions are not supported. They were at one point, but I think I was rather unclear on what you could realistically call during a signal handler, and they seemed to be a problem. Generally if you can handle signals with signalfd() it is better, but obviously you do need to poll it. May be able to work out whats needed for signal handlers (eg disabling gc in the function probably necessary, there are limited functions you can call).
