### ISSUE TITLE
getcpu() call appears not to work

### ISSUE THREAD

**Issue by wingo** [justincormack/ljsyscall#194]
If I `getcpu().cpu` within a process run with taskset -c 6, it returns 0 for me.  However if I `S.sched_getaffinity()`, that correctly returns the equivalent of `{6}`.

**Comment by justincormack** [comment]
Hmm, what does `strace` say?

**Comment by kbara** [comment]
The behaviour is the same in the ljsyscall with Snabb as with current master ( 214550af0cac3d07eb6d25ef64d2a4309b8fba1b ).

```cat cputestscript.lua```
```
local S = require("syscall")
print("getcpu", S.getcpu().cpu )
print("sched aff", S.sched_getaffinity())
```

```strace taskset -c 3 luajit cputestscript.lua```

Strace output includes:
```
getcpu([0], [0], 0)                     = 0
sched_getaffinity(0, 128, {8, 0, 0, 0}) = 32
```

The program prints:
```
getcpu	0
sched aff	{3}
```

**Comment by kbara** [comment]
I've PR'd a fix -  https://github.com/justincormack/ljsyscall/pull/195 - the problem was basically a typo in the source code ('node' was being given as an argument twice to getcpu, rather than cpu and node being given once each.)

**Comment by wingo** [comment]
Very nice, @kbara!  I stared at that for some time and couldn't figure it out :)

**Comment by justincormack** [comment]
merged, so closing this.
