### ISSUE TITLE
SEEK_DATA and SEEK_HOLE support for linux

### ISSUE THREAD

**Issue by tst2005** [justincormack/ljsyscall#207]
Hello,

I'm interested to be able to play (on linux) with sparse file by reading file content with SEEK_HOLE.

Since linux kernel 3.1, [SEEK_DATA and SEEK_HOLE](https://github.com/torvalds/linux/blob/5084fdf081739b7455c7aeecda6d7b83ec59c85f/include/uapi/linux/fs.h#L37-L38) has been added.

The ljsyscall's seems [already support c.SEEK.DATA and c.SEEK.HOLE](https://github.com/torvalds/linux/blob/5084fdf081739b7455c7aeecda6d7b83ec59c85f/include/uapi/linux/fs.h#L37-L38) for freebsd.

how hard is it to also support c.SEEK.DATE and c.SEEK.HOLE for linux ?

Regards,

**Comment by justincormack** [comment]
Hi, added a PR for the constants, #208 that should be all thats needed.

**Comment by justincormack** [comment]
Let me know if thats working for you.

**Comment by tst2005** [comment]
Thanks for your quick fix. I will test it.
