### ISSUE TITLE
netlink neighbors code returns rtmsg instead of ndmsg

### ISSUE THREAD

**Issue by sileht** [justincormack/ljsyscall#219]
Hi,

When we use nl.*neigh methods we got the wrong data type (rtmsg instead of ndmsg) for the returned object, so many fields of the structure cannot be retrieved.

Regards,

**Comment by justincormack** [comment]
Hmm, ok looks like one of the config tables is wrong...

**Comment by sileht** [comment]
I proposed this to fix it: https://github.com/justincormack/ljsyscall/pull/220

**Comment by justincormack** [comment]
fixed via #220
